### ISSUE TITLE
Convert existing ACF repeater to a new field key name

### ISSUE THREAD

**Issue by JiveDig** [Hube2/custom-field-converter#9]
Hey John!

I'm curious if this plugin can convert a repeater named 'old_repeater' to a different key 'new_repeater'? I want to keep all the same sub fields and data, just change keys.

**Comment by Hube2** [comment]
Actually, this plugin was created to only change ACF fields to standard WP fields to make it easier to do queries and not need to use things like `LIKE "1"` and so on. I honestly don't even know if this plugin still works. I do this on a field by field basis when I need it and building sites because this creates a lot less overhead than this plugin uses.

But no, this can't help with changing the name of a repeater or moving content from one repeater to another. My best advice if you really want to do this is this is to change the name of the field using phpMyAdmin, but this can only be done efficiently if the field name is unique across your entire site. 

The best choice is really to live with the old field name, which is what I generally do. Once a site is in operation with a lot of data added, I'll change the label, but the name will be the same. To be honest, I use field keys for ACF functions more than half the time anyway.

**Comment by JiveDig** [comment]
Thanks John. This is for a re-usable plugin that we changed the infrastructure on. We're going to use it on a few bigger sites, but it's only on 1 right now so I think we're just going to manually convert. All good.
